physics_quiz = [
   {"question": "What is the value of the magnitude of charge of electron? (a= 3x10^8, b= 1.6x10^19, c= 1.6x10^-19)",
    "answer": "c"},
   {"question": "What is the formula for calculating kinetic energy? (a= KE=mv^2, b= KE=1/2mv^2, c= KE=mgh)",
    "answer": "b"},
    {"question": "State Ohm's law. (a= V=IR, b= P=IV, c= E=mc^2)",
    "answer": "a"},
    {"question": "What is the value of the acceleration due to gravity on Earth? (a= 9.8m/s, b= 9.8m/s^2, c= 9m/s^2)",
    "answer": "b"},
    {"question": "What is the unit of electric current? (a= Volt, b= Watt, c= Ampere)",
    "answer": "c"},
    {"question": "What is the speed of light in a vacuum? (a= 3x10^8 m/s, b= 1.5x10^8 m/s, c= 3x10^6 m/s)",
    "answer": "a"},
    {"question": "What is Hooke's Law? (a= F = ma, b= F = kx, c= F = mg)",
    "answer": "b"},
    {"question": "What is the principle of conservation of energy? (a= Energy cannot be created or destroyed, only transferred or transformed, b= Energy can be created and destroyed, c= Energy is always conserved in a closed system)",
    "answer": "a"},
    {"question": "What is the unit of frequency? (a= Hertz (Hz), b= Newton (N), c= Joule (J))",
    "answer": "a"},
    {"question": "What is the formula for pressure? (a= P = F/A, b= P = mgh, c= P = V/I)",
    "answer": "a"}
]

maths_quiz = [
    {"question": "What is the derivative of x^2? (a= x^2, b= x, c= 2x)",
     "answer": "c"},
    {"question": "What is the integral of 2x dx? (a= x^2 , b= 2x + C, c= x^2 + C)",
     "answer": "c"},
    {"question": "What is the formula for the area of a triangle? (a= 1/2 base * height, b= base * height, c= 2 * base * height)",
     "answer": "a"},
    {"question": "What is the quadratic formula? (a= x = (-b ± √(b^2 - 4ac)) / 2a, b= x = (-b ± √(b - 4ac)) / 2a, c= x = (b ± √(b^2 - 4ac)) / 2a)",
     "answer": "a"},
    {"question": "What is the value of sin(90 degrees)? (a= 0, b= 1, c= -1)",
     "answer": "b"},
    
    {"question": "What is the derivative of sin(x)? (a= cos(x), b= -sin(x), c= -cos(x))",
     "answer": "a"},
    {"question": "What is the integral of 1/x dx? (a= ln|x| + C, b= 1/x + C, c= x + C)",
     "answer": "a"},
    {"question": "What is the sum of the angles in a triangle? (a= 180 degrees, b= 90 degrees, c= 360 degrees)",
     "answer": "a"},
    {"question": "What is the value of cos(0 degrees)? (a= 0, b= 1, c= -1)",
     "answer": "b"},
    {"question": "What is the formula for the circumference of a circle? (a= πd, b= 2πr, c= πr^2)",
     "answer": "a"}
]

business_quiz = [
    {"question": "What is the definition of market segmentation? (a= The process of dividing a market into distinct groups of buyers, b= The process of targeting all customers with the same marketing strategy, c= The process of selling all products at the same price)",
     "answer": "a"},
    {"question": "What is the primary purpose of a SWOT analysis? (a= To analyse employee performance, b= To determine the cost of production, c= To evaluate the internal and external environment)",
     "answer": "c"},
    {"question": "What does 'ROI' stand for in business? (a= Return on Inventory, b= Return on Investment, c= Return on Income)",
     "answer": "b"},
    {"question": "What is a 'brand'? (a= A name, term, design, or symbol that identifies one seller's product, b= A pricing strategy, c= A financial statement)",
     "answer": "a"},
    {"question": "What is 'market research'? (a= The action or activity of gathering information about consumers' needs and preferences, b= The process of hiring new employees, c= The strategy for setting prices)",
     "answer": "a"},
    {"question": "What is the purpose of a balance sheet? (a= To show the financial position of a business at a particular point in time, b= To calculate the profit or loss of a business over a period of time, c= To show the cash flow in and out of a business)",
     "answer": "a"},
    {"question": "What is the role of human resource management? (a= Managing the finances of a business, b= Overseeing the production process, c= Managing the recruitment, development, and welfare of employees)",
     "answer": "c"},
    {"question": "What is a stakeholder? (a= An individual or group with an interest in the success of a business, b= A company's competitor, c= A financial institution that lends money to a business)",
     "answer": "a"},
    {"question": "What is the break-even point? (a= The point where a business makes a profit, b= The point where total revenue equals total costs, c= The point where a business experiences a loss)",
     "answer": "b"},
    {"question": "What is meant by 'corporate social responsibility'? (a= A company's commitment to manage its social, environmental, and economic effects responsibly, b= A company's strategy to maximize profits, c= A company's marketing campaign)",
     "answer": "a"}
]